#!/bin/bash
#SBATCH -A m4142_g
#SBATCH -C gpu
#SBATCH -q regular
#SBATCH -t 360:00
#SBATCH -n 128
#SBATCH -c 1
#SBATCH -G 128
#SBATCH --gpus-per-task=1
#SBATCH -o qpe_h2o

export SLURM_CPU_BIND="cores"

source /global/homes/a/angli/sc22/src/setup_perlmutter.sh
srun -C gpu -N 128 -n 512 --gpus-per-task=1 --gpu-bind=single:1 /global/homes/a/angli/sc22/src/qpe/qpe_nvgpu /global/homes/a/angli/sc22/src/qpe/py_out.json
